In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings(action = 'ignore')

In [25]:
df = pd.read_csv("dataset.csv")

In [26]:
df.drop("Unnamed: 0", axis = 1, inplace=True)

In [27]:
df

User_ID  Personal  Theme  comment_day  Participant Type  \
0       ID_000H9XOP_Month_5      -1.0   -1.0          0.0               0.0   
1       ID_003YJHQA_Month_4      -1.0   -1.0          0.0               0.0   
2       ID_004UKSJV_Month_1      -1.0   -1.0          0.0               0.0   
3      ID_004UKSJV_Month_12      -1.0   -1.0          0.0               0.0   
4       ID_008D2J6C_Month_1      -1.0   -1.0          0.0               0.0   
...                     ...       ...    ...          ...               ...   
17386   ID_ZZMHNLNT_Month_4      -1.0   -1.0          0.0               0.0   
17387   ID_ZZQK0LU6_Month_3      -1.0   -1.0          0.0               1.0   
17388   ID_ZZUNZJ2U_Month_2      -1.0   -1.0          0.0               0.0   
17389   ID_ZZVM2KO7_Month_4      -1.0   -1.0          0.0               0.0   
17390   ID_ZZVUJ45W_Month_3      -1.0   -1.0          0.0               1.0   

       Successful Submission Count  competition_enrollment_day FeatureA  \
0                                0                         0.0       -1   
1                                0                         0.0       -1   
2                                0                         0.0       -1   
3                                0                         0.0       -1   
4                                0                         0.0       -1   
...                            ...                         ...      ...   
17386                            0                         0.0       -1   
17387                            0                        29.0      [2]   
17388                            0                         0.0       -1   
17389                            0                         0.0       -1   
17390                            0                         5.0      [1]   

      FeatureB  FeatureC  ...  competition started hour  \
0           -1      -1.0  ...                        -1   
1           -1      -1.0  ...                        -1   
2           -1      -1.0  ...                        -1   
3           -1      -1.0  ...                        -1   
4           -1      -1.0  ...                        -1   
...        ...       ...  ...                       ...   
17386       -1      -1.0  ...                        -1   
17387       []      28.0  ...                         9   
17388       -1      -1.0  ...                        -1   
17389       -1      -1.0  ...                        -1   
17390      [7]       4.0  ...                         6   

       competition started minute  competition started second  \
0                              -1                          -1   
1                              -1                          -1   
2                              -1                          -1   
3                              -1                          -1   
4                              -1                          -1   
...                           ...                         ...   
17386                          -1                          -1   
17387                           0                           0   
17388                          -1                          -1   
17389                          -1                          -1   
17390                           0                           0   

      User sign-in hour User sign-in minute User sign-in second  \
0                    15                  18           11.439200   
1                    10                  30           32.261855   
2                    -1                  -1           -1.000000   
3                     8                  32           14.997443   
4                     9                  42           39.695313   
...                 ...                 ...                 ...   
17386                10                  55           11.435972   
17387                 9                  48           48.866739   
17388                22                  15           18.135850   
17389     

In [28]:
df["Month"] = df["User_ID"].str[18:]
df["Month"] = pd.to_numeric(df["Month"])

In [29]:
df["Month"].unique()

array([ 5,  4,  1, 12,  2,  3, 11], dtype=int64)

In [37]:
df_train = df[(df["Month"]== 1) | (df["Month"]== 2) | (df["Month"]== 3) | (df["Month"]== 4) | (df["Month"]== 11) | (df["Month"]== 12)]

In [38]:
df_train["Month"].unique()

array([ 4,  1, 12,  2,  3, 11], dtype=int64)

In [39]:
df_train.shape

(14906, 53)

In [40]:
df_test = df[df["Month"]== 5]

In [41]:
df_test["Month"].unique()

array([5], dtype=int64)

In [42]:
df_test.shape

(2485, 53)

## CLUSTERING

In [44]:
from sklearn.cluster import KMeans

In [46]:
df_train.drop("User_ID", axis=1, inplace=True)

In [47]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 14906 entries, 1 to 17390
Data columns (total 52 columns):
 #   Column                                Non-Null Count  Dtype  
---  ------                                --------------  -----  
 0   Personal                              14906 non-null  float64
 1   Theme                                 14906 non-null  float64
 2   comment_day                           14906 non-null  float64
 3   Participant Type                      14906 non-null  float64
 4   Successful Submission Count           14906 non-null  int64  
 5   competition_enrollment_day            14906 non-null  float64
 6   FeatureA                              14906 non-null  object 
 7   FeatureB                              14906 non-null  object 
 8   FeatureC                              14906 non-null  float64
 9   FeatureD                              14906 non-null  float64
 10  FeatureE                              14906 non-null  float64
 11  SecretCode     

In [48]:
from sklearn.decomposition import PCA
pca = PCA(n_components=2).fit(df_train)

ValueError: could not convert string to float: '[]'

In [53]:
kmeans = KMeans(init='k-means++', n_clusters=2, n_init=2)

In [ ]:
kmeans.fit(X)

In [ ]:
P = kmeans.predict(X)

In [ ]:
colors = list(map(lambda x: '#3b4cc0' if x == 1 else '#b40426', P))
plt.scatter(X[:,0], X[:,1], c=colors, marker="o", picker=True)
plt.title('Two clusters of data')
plt.xlabel('Temperature yesterday')
plt.ylabel('Temperature today')
plt.show()